
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise32"
  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.network :private_network, ip: "192.168.20.14"
  config.vm.network :forwarded_port, guest: 3000, host: 3000

  config.ssh.port = 2222
end

