
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise32"
  config.vm.provision :shell, path: "install-curl.sh"
  config.vm.provision :shell, path: "install-nodejs.sh"
  config.vm.provision :shell, path: "install-rvm.sh",  args: "stable"
  config.vm.provision :shell, path: "install-ruby.sh", args: "2.0.0"
  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.network :private_network, ip: "192.168.20.14"
  config.vm.network :forwarded_port, guest: 3000, host: 3000

  config.ssh.port = 2222
end

