default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000


development:
  <<: *default
  database: picklr_development

test: &test
  <<: *default
  database: picklr_test

production:
  <<: *default
  database: picklr_production

cucumber:
  <<: *test